name: Windows CI/CD

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
      # -------------------
      # Checkout
      # -------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # -------------------
      # Cache vcpkg
      # -------------------
      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: C:/vcpkg/packages
          key: vcpkg-${{ runner.os }}-sfml-${{ matrix.config }}

      # -------------------
      # Install vcpkg if cache missed
      # -------------------
      - name: Install vcpkg
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:/vcpkg
          C:/vcpkg/bootstrap-vcpkg.bat

      # -------------------
      # Install SFML 3
      # -------------------
      - name: Install SFML 3
        run: C:/vcpkg/vcpkg install sfml:x64-windows

      # -------------------
      # Configure CMake
      # -------------------
      - name: Configure CMake
        run: cmake -S . -B build ^
              -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ^
              -DVCPKG_TARGET_TRIPLET=x64-windows ^
              -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      # -------------------
      # Build
      # -------------------
      - name: Build
        run: cmake --build build --config ${{ matrix.config }}

      # -------------------
      # Copy SFML DLLs into build folder
      # -------------------
      - name: Copy SFML DLLs
        run: Copy-Item "C:/vcpkg/installed/x64-windows/bin/*.dll" -Destination "build/${{ matrix.config }}/" -Recurse
        shell: pwsh


      # -------------------
      # Package build folder into a zip
      # -------------------
      - name: Package artefact
        run: |
          powershell Compress-Archive -Path build/${{ matrix.config }}/* -DestinationPath build/${{ matrix.config }}/game-${{ matrix.config }}.zip

      # -------------------
      # Upload artefact
      # -------------------
      - name: Upload Build Artefacts
        uses: actions/upload-artifact@v4
        with:
          name: game-${{ matrix.config }}
          path: build/${{ matrix.config }}/game-${{ matrix.config }}.zip
